#153009245 configure eslint
andela/k2-cfh pull request #12
Opened 2017-11-21 18:21 UTC by oti4me

#### What does this PR do?

Configure ESLint

#### Description of Task to be completed?

- Install ESLint and other dependencies
- Run eslint --init and choose the airbnb popular style guide
- Configure the generated .eslintrc.yml file to include the airbnb style rules

#### How should this be manually tested?

- Clone online repository
- Navigate to the cloned directory
- Add ESLint as extension to your favourite text editor
- Run npm install
- Open the codebase in your favourite text editor to see linting errors
- Run: npm run eslint on your command prompt to test for linting errors

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

- story type: chore
- story id: 153009245
- story title: Configure ESLint

**Screenshots (if appropriate)**

<img width="1440" alt="screen shot 2017-11-21 at 7 16 26 pm" src="https://user-images.githubusercontent.com/14099353/33089363-a195331a-cef0-11e7-9adb-59b75f370a24.png">

2017-11-21 18:42 UTC, temilaj commented on npm-debug.log
> +0 info it worked if it ends with ok
Why do you we have this file in our repo?

2017-11-21 18:43 UTC, temilaj requested changes
I'm curious to know why we're using the .yml configuration file. How well will this work with houndci?

2017-11-21 19:09 UTC, oti4me commented
@temilaj I have made the changes you pointed. I have convert the .eslintrc.yml file to .eslintrc file and have remove the npm-debug.log file from the repository.

2017-11-22 11:35 UTC, temilaj requested changes
Good work improving your PR. 
However we now have 5 commits that are essentially the same. Take time out to squash these commits into 1, and then raise another PR

2017-11-22 11:50 UTC, closed without merging